import "./globals.css";
import { Nunito,Montserrat } from "next/font/google";
import { Cx } from "../utils/fillee";
import Header from "../components/Header";

const nunito = Nunito({ subsets: ['latin'], display: "swap", variable: "--font-nt" })
const montserrat = Montserrat({ subsets: ['latin'], display: "swap", variable: "--font-me" })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={Cx(nunito.variable, montserrat.variable,"font-me bg-light")}>
        
        <Header/>
        {children}</body>
    </html>
  )
}
